### ISSUE TITLE
Unhandled Promise in logHMS100TF(data)

### ISSUE THREAD

**Issue by zapalotta** [foxthefox/ioBroker.jeelink#108]
After installing latest instance of jee link on ioBroker on RaspberryOS, sensor discovery fails:

`2023-02-15 09:41:56.653  - debug: jeelink.1 (16919) data received: H002500290240
2023-02-15 09:41:56.675  - error: jeelink.1 (16919) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-02-15 09:41:56.676  - error: jeelink.1 (16919) unhandled promise rejection: tmpp is not defined
2023-02-15 09:41:56.683  - error: jeelink.1 (16919) ReferenceError: tmpp is not defined
    at logHMS100TF (/opt/iobroker/node_modules/iobroker.jeelink/jeelink.js:493:28)
    at ReadLineParser.<anonymous> (/opt/iobroker/node_modules/iobroker.jeelink/jeelink.js:1592:21)
    at ReadLineParser.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at ReadLineParser.Readable.push (node:internal/streams/readable:228:10)
    at ReadLineParser._transform (/opt/iobroker/node_modules/iobroker.jeelink/node_modules/@serialport/parser-delimiter/lib/index.js:35:12)
    at ReadLineParser.Transform._write (node:internal/streams/transform:205:23)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
2023-02-15 09:41:56.685  - error: jeelink.1 (16919) tmpp is not defined`

The corresponding code in jeelink.js shows that the variable temp has never been defined:

`
function logHMS100TF(data){
    var tmp = data.split('');
    if(tmp[0]==='H'){                      // Wenn ein Datensatz sauber gelesen wurde
        // somit werden alle SenderIDs bearbeitet
        var buf = new Buffer(tmp);
        var eid = parseInt(tmpp[3])*10 + parseInt(tmpp[4]); //empfangene ID
        var array=getConfigObjects(adapter.config.sensors, 'sid', eid);
`

Any help appreciated.

**Comment by foxthefox** [comment]
can you please instal the version from github, it seems that you have an older version of the adapter
this should be solving the issue
